
x=10
print(x)
print("Hello, world!")
print("Welcome to Python programing.")
print("This is multi-line printing.")
print(f"The result of {15} + {4} is: {15 + 4}")
print(f"The result of {15} - {4} is: {15 - 4}")
print(f"The result of {15} * {4} is: {15 * 4}")
print(f"The result of {15} / {4} is: {15 / 4}")
print(f"The result of {15} ** {4} is: {15 ** 4}")
print(f"The result of {15} // {4} is: {15 // 4}")
print("The sum of 5 and 3 is", 5 + 3)
print("The product of 4 and 7 is", 4 * 7)
print("5", "+", "3", "=", 5 + 3, sep=" ") 
print("4", "*", "7", "=", 4  *7, sep=" * ")
print("5 + 3 =", end=" ")
print(5 + 3)
print("4 * 7 =", end=" ")
print(4 * 7)